config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/relationships/build', to: 'relationships#create', :as => "follwers"
  # resources :relationships
  resources :users 
  resources :chirps do
    resources :squwaks
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # resources :users do
  #   resources :chirps do
  #     resources :squwaks
  #   end 
  #   resources :chirps do
  #     resource :squwaks
  

end 
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chirp.rb
class Chirp < ApplicationRecord

    belongs_to :user
    has_many :squwaks, dependent: :destroy

end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :user
    belongs_to :follower
    # has_many :followers, :through => :relationships, :source => User
    

end

app/models/splat.rb
class Splat < ApplicationRecord

    belongs_to :user
    belongs_to :chirp

end

app/models/squwak.rb
class Squwak < ApplicationRecord

    belongs_to :user
    belongs_to :chirp

end

app/models/user.rb
class User < ApplicationRecord

    has_many :chirps
    # has_many :squwaked_chirps, through: :squwaks, source: :chirp
    has_many :squwaks, dependent: :destroy
    # has_many :followers, :class_name => “Relationship”, :foreign_key => “user_id”
    # has_many :following, :class_name => “Relationship”, :foreign_key => “follower_id”
    has_many :relationships, class_name: "User" 
    has_many :followers, :through => :relationships

    has_secure_password

    # validates :username, presence: true
    # validates :username, uniqueness: true
    # validates :password, presence: true, length: {minimum: 8}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        user_id = session[:user_id]
        user_id && User.find(user_id)
    end

    def authenticate!
        unless current_user
            flash[:info] = "You have to be logged in to do that!"
            redirect_to new_chirp_path
        end
    end

     

end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController

    # before_action :require_login

    def index
        @chirps = Chirp.all
        @chirp = Chirp.new
        @users = User.all
    end 
    
    def new
        @chirp = Chirp.new
    end

    def show
        @chirp = Chirp.find(params[:id])
        @chirps = Chirp.all
    end 

    # def create
    #     @chirp = Chirp.new
    # end

    def create
        @chirp = Chirp.new(chirp_params)
        if @chirp.save
        redirect_to user_path(@chirp.user)
        else
        render :new
        end
    end


    private

    def chirp_params
        params.require(:chirp).permit(:user_id, :content, :chirp_id, :squwaks)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
#     before_action :find_user

    def index
    end 

    def new
        # @relationship = Relationship.new
        @users = User.all
    end 

#     # def create
#     #     @users = User.all
#     #     @relationship = current_user.relationships.build(:follower_id => params[:follower_id])
#     #     @relationship.user_id = session[:user_id]
#     #     if @relationship.save
#     #       flash[:notice] = "Added follower."
#     #       redirect_to chirps_path
#     #     else
#     #       flash[:notice] = "Unable to add follower."
#     #       redirect_to chirps_path
#     #     end
#     #   end

#     def create 
         
#         @user.relationships.create(id: current_user.id)
       
#         redirect_to chirps_path
#     end

# # #   def create 
# # #     @user.followers.create(user_id: current_user.id)
# # #     redirect_to user_path(@user)
# # #   end

# #   private

#     def find_user
#       @user = User.find(params[:format])
#     end

      
#     def relationship_params
#         params.require(:relationship).permit(:user_id, :follower_id)
#         #need to add authenticate above?
#     end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:info] = "Login Successful!"
        redirect_to chirps_path
        else
            @error = "No such username or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to users_path
    end
end

app/controllers/squwaks_controller.rb
class SquwaksController < ApplicationController

#     before_action :authenticate_user!

# #   def create
# #     @squwak = Squwak.new(chirp_id: params[:chirp_id], user: current_user)
# #     # respond_to do |format|
# #     #   format.js
# #     end
# #   end

#     def new
#         @squwak = Squwak.new(squwak_params)
#     end

#   def create
#     @user = current_user.id
#     @chirp = params[:chirp_id]
#     squwaks = {user_id: @user, chirp_id: @chirp}
#     @squwak = Squwak.new(squwaks)

#     @squwak.save!
#     if @squwak.save
#       redirect_to chirps_path
#     else
#      redirect_to chirp_path
#     end
#   end

before_action :find_chirp
# before_action :find_squwak, only: [:destroy]

  def create 
    @chirp.squwaks.create(user_id: current_user.id)
    redirect_to chirp_path(@chirp)
  end

  private

    def find_chirp
      @chirp = Chirp.find(params[:chirp_id])
    end

    def squwak_params
      params.require(:squwak).permit(:user_id, :chirp_id, :current_user)
    end

    # def find_squwak
    #     @squwak = @chirp.squwaks.find(params[:id])
    # end

    # def destroy
    #     @chirp.squwaks.destroy(user_id: current_user.id)
    #     if !(already_squwaked?)
    #       flash[:notice] = "Cannot unsquwak"
    #     else
          
    #   @squwak.destroy
    #     end
    #     redirect_to chirps_path
    #   end

#   def destroy
#     @favorite = Favorite.find(params[:id])
#     respond_to do |format|
#       format.js
#     end
#   end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    # before_action :require_login, except: [:new, :create]

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
        @user.chirps.build
      end
    
      def create
        @user = User.new(user_params)
        if @user.save
          redirect_to user_path(@user)
        else
          render :new
        end
      end
    



    private

    def user_params
        params.require(:user).permit(:username, :bio, :password, :profile_pic, :password_confirmation, :follower_id)
        #need to add authenticate above?
    end

    # def password_match?
    #     params[:user][:password] == params[:user][:password_confirmation]
    # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chirps_helper.rb
module ChirpsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/squwaks_helper.rb
module SquwaksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chirps/_feed.html.erb
<h1>Chirrp Feed</h1>

<%= render 'chirrps/index' %>

app/views/chirps/index.html.erb
<h1>Chirps!</h1>


<h3>Create New Chirp: <%= link_to "Write a new Chirp!", new_chirp_path %></h3><br>
<br>

<ul>
<% @chirps.reverse.each do |chirp| %>
<br>
  
<strong>@<%= link_to chirp.user.username, user_path(chirp.user_id) %></strong>
<%= chirp.created_at.strftime("%m/%d/%Y at %I:%M%p") %>
<p><%= chirp.content %></p>
<%= image_tag("https://media.giphy.com/media/11ec1pd0tpSFUc/giphy.gif", :alt => "smiley_face_gif") %><br>

 <%= button_to 'Sqwuak', chirp_squwaks_path(chirp), method: :post %> 
 <%= button_to 'Follow', follwers_path(chirp.user_id), method: :get %>

 <p><%= chirp.squwaks.count %> <%= (chirp.squwaks.count) == 1 ? 'Sqwuak' : 'Sqwuaks'%></p>
 
 
 
 
<br><br>
<% end %>

</ul>

app/views/chirps/new.html.erb
<h1>New Chirp Form</h1>

<%= form_for(@chirp) do |f| %>
<%= f.label :content %>
<%= f.text_field :content %>
<br><br>
<%= f.label :user_id %>
<%= f.text_field :user_id %>
<br><br>
<%= f.submit %>
<% end %>

app/views/chirps/show.html.erb
<h1>Profile Page for my chirp:</h1>
<h2><%= @chirp.content %></h2>

Chirp by: <%= @chirp.user.username %>
<br>
Squwaks: <%= @chirp.squwaks.count %>
<br>
Chirp created: <%= @chirp.created_at.strftime("%d %b %Y at %I:%M %p") %>
<br>



<%= link_to "Homepage", chirps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChirpApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>All Chirp Users</h1>

<ul>

<% @users.each do |user| %>
<li> <%=link_to user.username, user_path(user)%></li>
<p><%= user.username %></p>
<%= user.chirps.each do |chirp| %>
<p><%= chirp.content %></p>
<% end %>
<% end %>


  


 

app/views/users/new.html.erb
<h1>Create Chirps account</h1>


<%= form_for @user do |f| %>
  <%= f.label :username %>:
  <%= f.text_field :username %><br>

  <%= f.label :bio %>:
  <%= f.text_area :bio %><br>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :profile_pic %>
  <%= f.text_field :profile_pic %>



  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Profile Page for <%= @user.username %></h1>

<h2><%= link_to "Home", chirps_path(@chirps) %></h2>

<p><%= @user.username %></p>
<% @user.chirps.reverse.each do |chirp| %>
<p><%= link_to chirp.content, chirp_path(chirp) %></p>
<% end %>

<img src= "<%=@user.profile_pic%>">

<p>Username: <%=h @user.username %></p>
<p><%= link_to "Who to Follow", users_path %></p>